[project]
name = "EduQueue"
version = "0.1.0"
authors = [{ name="todo"}]
description = "todo"
requires-python = ">=3.8"
dependencies = [
    "psycopg2 >= 2.9.10",
    "pytest >= 8.3.0"
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-rfE"
testpaths = [
    "test"
]
